repos:
- repo: local
  hooks:
    - id: spotless-apply
      name: spotless-apply
      description: "Run SpotlessJavaApply on Gradle"
      files: '.*\.java$'
      entry: ./gradlew spotlessJavaApply
      language: system
      pass_filenames: false
      require_serial: true
      types_or: [java]